### ISSUE TITLE
2021 Q1-Q2 Roadmap

### ISSUE THREAD

**Issue by ivanoats** [orcasound/orcamap-react#23]
**Roadmap**
For March and the next few months 2021

- [ ] Make vector layer for google sheets

- [ ] Connect google sheets info in useEffect() in mapContainer

- [ ] Deploys in prod, stage, and PR previews on Netlify working

- [ ] Make separate vector layer with hydrophone coordinates and image

**Comment by Devesh21700Kumar** [comment]
Hey @ivanoats I had started contribution towards the codebase just recently and would like to proceed with the above mentioned phase targets
Could u provide some more insight about what data do we exactly need in the vector layer?

**Comment by Devesh21700Kumar** [comment]
@ivanoats i've connected google sheets info in useEffect() in mapContainer and have refactored the setCoordinates type as well..
Do check the PR

**Comment by arnab15** [comment]
Hey, @ivanoats  I had just finished setting up the development environment.Can you please guide me a little bit so that I can change and improve littlebit?

**Comment by ivanoats** [comment]
> Hey, @ivanoats I had just finished setting up the development environment.Can you please guide me a little bit so that I can change and improve littlebit?

This isn't a roadmap comment.  Please use #orcamap-react Slack for getting guidance from the group, as I may not be available for 1:1 communication.

**Comment by scottveirs** [comment]
I have it on my list to port all old feature requests that make sense from the old orcamap project (Mapbox) to a new Github project here... but for now here's a link -- [old orcamap development Trello board](https://trello.com/b/MfDaW3P6/orcamap-development)
